default:
    - override hydra/output: local
    - override hydra/launcher: local

# general inputs
kitchen_task      :   BB
env               :   kitchen-${kitchen_task}-v0      # placeholder name
algorithm         :   NPG
seed              :   123
sample_mode       :   trajectories
rl_num_traj       :   200
rl_num_samples    :   0                       # will be ignored when sample_mode=trajectories
num_cpu           :   20
rl_num_iter       :   5001
save_freq         :   50
eval_rollouts     :   10
exp_notes         :  'Kitchen 2 primitive training.'

# RL parameters (all params related to PG, value function etc.)
policy_size       :   (64, 64)
init_log_std      :   -0.1
min_log_std       :   -1.0
vf_hidden_size    :   (128, 128)
vf_batch_size     :   64
vf_epochs         :   2
vf_learn_rate     :   1e-3
rl_step_size      :   0.05
rl_gamma          :   0.995
rl_gae            :   0.97

# Algorithm hyperparameters : if alg requires additional params, can be specified here (or defaults will be used)

alg_hyper_params  :   {'device': 'cpu'}

# general outputs
job_name          :   kitchen_${kitchen_task}_RERUN_DEBUG

hydra:
    job:
        name: ${job_name}
